#!/usr/bin/python3
import sys
import os
import logging
from lib import print_info, print_error, get_log_location, LOGGING_FORMAT

def empty_zone(zone_name):
    return """$TLL 60480
@   IN  SOA %s webmaster.ucll.be (
                   1    ; Serial
              604800    ; Refresh
               86400    ; Retry
             2419200    ; Expire
                8640 )  ; Negative cache ttl
    IN  NS  ns1.uclllabs.be
    IN  NS  ns2.uclllabs.be
    IN  A   193.191.177.180
""" % (zone_name)

def get_zone_file_location(zone_name):
    return "/etc/bind/zones/db.%s.robin-vandenbroeck.sb.uclllabs.be" % (zone_name)

def add_zone(zone_name, zone_file_location, zone_content):
    exists = os.path.isfile(zone_file_location)
    if exists:
        print_error("Cannot create allready exisiting zone")
    try:
        with open(zone_file_location, "w+") as file:
            logging.info("Adding zone db file for zone %s located at %s"
                         % (zone_name, zone_file_location))
            file.write(zone_content + "\n")
    except IOError:
        print_error("Could not write to: %s" % (zone_file_location))

def add_to_named(zone_name, zone_file_location):
    bind_file_location = "/etc/bind/named.conf.script"
    try:
        with open(bind_file_location, "a") as file:
            content = """
zone %s {
    type master;
    notify yes;
    file "%s"
};
""" % (zone_name, zone_file_location)
            logging.info("Adding %s to %s" % (zone_name, zone_file_location))
            file.write(content)
    except IOError:
        print_error("Could not write to %s" % (bind_file_location))


if __name__ == '__main__':
    # Setup logging
    logging.basicConfig(level=logging.DEBUG, filename=get_log_location("dns_add_zone"),
                        format=LOGGING_FORMAT, filemode="a+")
    args = sys.argv

    logging.debug("Command issued: " + " ".join(args))

    # Don't need the name of the script
    args.pop(0)
    try:
        zone_name = args[0]
    except IndexError:
        print_error("Please enter a zone")

    zone_file_location = get_zone_file_location(zone_name)
    zone_content = empty_zone(zone_name)
    add_zone(zone_name, zone_file_location, zone_content)
    add_to_named(zone_name, zone_file_location)

    logging.info("Reloading bind9")
    #os.system("systemctl restart bind9")
