#!/usr/bin/python3
import os
import sys
import logging
from lib import print_error, get_log_location, LOGGING_FORMAT

def document_root(vhost):
    return "/etc/www/scripts/%s" % (vhost)

def write_index(vhost):
    filename = document_root(vhost) + "/index.html"
    content = "hello " + (vhost)

    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w") as f:
        logging.info("Writing '%s' to %s" % (content, filename))
        f.write(content)

def create_vhost_config(vhost):
    vhost_document_root = document_root(vhost)
    return """
http://%s {
    root %s
    gzip
    log /var/log/http/access-%s.log
    errors /var/log/http/error-%s.log
}""" % (vhost, vhost_document_root, vhost, vhost)

def add_vhost_config_to_caddy(vhost_config):
    caddyfile_location = "/etc/caddy/Caddyfile.script"
    with open(caddyfile_location , "a") as file:
        logging.info("Writing vhost config to %s" % (caddyfile_location))
        file.write(vhost_config)

if __name__ == '__main__':
    # Setup logging
    logging.basicConfig(level=logging.DEBUG, filename=get_log_location("http_add_vhost"),
                        format=LOGGING_FORMAT, filemode="a+")
    args = sys.argv

    logging.debug("Command issued: " + " ".join(args))

    # Don't need the name of the script
    args.pop(0)
    try:
        vhost = args[0]
    except IndexError:
        print_error("Please enter a vhost")

    config = create_vhost_config(vhost)

    write_index(vhost)
    add_vhost_config_to_caddy(config)

    logging.info("Reloading caddy")
    os.system("systemctl restart caddy")
